language: generic 
sudo: require
services:
  - docker

before_install:
  - docker build -t kugeblitzz/docker-react-travis-test -f Dockerfile.dev . 

script:
  - docker run -e CI=true kugeblitzz/docker-react-travis-test npm run test -- --coverage